---
- name: '[Linux] Detect checkout type'
  shell: command -v svn
  register: svn_check
  ignore_errors: yes
  when:
    - nerdfonts_checkout == 'auto'
  become: yes
  become_user: root

- name: '[Linux] Use git clone to checkout'
  set_fact:
    nerdfonts_checkout: git
  when:
    - nerdfonts_checkout == 'auto'
    - svn_check.failed

- name: '[Linux] Use svn export to checkout'
  set_fact:
    nerdfonts_checkout: svn
  when:
    - nerdfonts_checkout == 'auto'
    - not svn_check.failed

- name: '[Linux] Export files from the nerdfonts repo'
  subversion:
    repo: "https://github.com/ryanoasis/nerd-fonts.git/trunk/patched-fonts/{{ item.fontname }}"
    dest: "{{ nerdfonts_git_dest }}/patched-fonts/{{ item.fontname }}"
    export: yes
  when:
    - nerdfonts_checkout == 'svn'
    - not item.installed
  with_items:
    - "{{ nerdfonts_exists }}"
  become: yes
  become_user: root

- name: '[Linux] Clone the nerdfonts repo'
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: "{{ nerdfonts_git_dest }}"
    depth: 1
    version: master
  when: 
    - nerdfonts_checkout == 'git'
    - false in nerdfonts_install_statuses
  become: yes
  become_user: root
