---
- block:
  - name: '[Debian] Include Dependencies installation tasks'
    include_tasks: dependencies.yml
  become: yes
  tags:
    - nerdfonts
    - nerdfonts_dependencies

- name: '[Debian] Clone the nerdfonts repo'
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: "{{ nerdfonts_git_dest }}"
    depth: 1
    version: master
  tags:
    - nerdfonts

# include tasks to loop
- name: '[Debian] Install fonts for nerdfonts_users'
  include_tasks: "install-fonts-Debian.yml"
  loop: "{{ nerdfonts_users }}"
  loop_control:
    loop_var: nerdfonts_user

- name: '[Debian] Remove nerdfonts repo'
  file:
    path: "{{ nerdfonts_git_dest }}"
    state: absent
...
