---
- block:
  - name: '[Debian] Include Dependencies installation tasks'
    include_tasks: dependencies.yml
  become: yes
  tags:
    - nerdfonts
    - nerdfonts_dependencies

- name: '[Debian] Clone the nerdfonts repo'
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: /tmp/nerd_fonts
    depth: 1
  tags:
    - nerdfonts

- name: '[Debian] Setting nerdfonts_install_dir for system-wide installation'
  set_fact:
    nerdfonts_install_dir: "{{ nerdfonts_deb_fonts_dir }}/NerdFonts"
  tags:
    - nerdfonts

- name: '[Debian] Create NerdFonts folder for installation'
  file:
    path: "{{ nerdfonts_install_dir }}"
    state: directory
  with_items: "{{ nerdfonts_users }}"
  become: yes
  become_user: "{{ item }}"
  tags:
    - nerdfonts

- name: '[Debian] Check if there are any NerdFonts already installed'
  stat:
    path: "{{ nerdfonts_install_dir }}/{{ item.fontname }}"
  with_items: "{{ nerdfonts_fonts }}"
  register: nerdfonts_stat
  tags:
    - nerdfonts

- name: '[Debian] Combine the results into dictionary with following structure: {<FontName> : <stat.exists>}'
  set_fact:
    # https://stackoverflow.com/questions/35605603/using-ansible-set-fact-to-create-a-dictionary-from-register-results
    # FLATTENING THE RESULTS AND COMBINING THEM INTO DICTIONARY WITH SPECIFIED KEY:VALUE STRUCTURE:
    #
    # IF nerdfonts_fonts IS DICTIONARY:
    # nerdfonts_exists: "{{ nerdfonts_exists|default({}) | combine( {item.item.value.fontname: item.stat.exists} ) }}"
    # IF nerdfonts_fonts IS LIST:
    nerdfonts_exists: "{{ nerdfonts_exists|default({}) | combine( {item.item.fontname: item.stat.exists} ) }}"
  with_items: "{{ nerdfonts_stat.results }}"
  tags:
    - nerdfonts

- name: '[Debian] Define nerdfonts_install_cmd'
  set_fact:
    nerdfonts_install_cmd: "rsync -av --exclude='*[Ww]indows*' --exclude='*.md'{% if not nerdfonts_mono %} --exclude='*Mono.ttf'{% endif %}"
  tags:
    - nerdfonts

- name: "[Debian] Install NerdFont -  {{ item.key }}"
  command: "{{ nerdfonts_install_cmd }} /tmp/nerd_fonts/patched-fonts/{{ item.key }} {{ nerdfonts_install_dir }}"
  with_dict: "{{ nerdfonts_exists }}"
  become: yes
  become_user: "{{ item }}"
  when:
    - not item.value
  tags:
    - nerdfonts

- name: '[Debian] Install specified NerdFonts'
  command: "fc-cache -f {{ nerdfonts_install_dir }}"
  # https://stackoverflow.com/questions/47523815/ansible-how-to-check-if-dictionary-has-at-least-one-specified-value
  # Execute command only when some dictionary contains at least one 'false' value:
  when: false in nerdfonts_exists.values()
  tags:
    - nerdfonts
...
